matrix:
  include:
  - os: osx
    language: generic
    osx_image: xcode10.1

before_install:
- pip3 install --upgrade pip setuptools wheel

install:
- pip3 install -r requirements.txt
- pip3 install certifi https://github.com/pyinstaller/pyinstaller/archive/develop.zip

script: pyinstaller --additional-hooks-dir=Hooks/ -y -F -n CurseBreaker -c --noupx CurseBreaker.py

deploy:
  provider: gcs
  skip_cleanup: true
  local-dir: dist
  on:
    repo: AcidWeb/CurseBreaker
  bucket: cursebreaker-deploy
  access_key_id: GOOG1EVRPTA3CKGCNHC5EMADHWYWVL7MJXLZRVLURJUKM3AT25F35L7PCI3DQ
  secret_access_key:
    secure: go9dVgfUwObRD5O9XSpQ6d8qNU7+rRMBm9ttoEvQ2uvh/B3rtsVu2LBMHn5bKLLhx4jpjCRR+gzpSIdWMkThWRQa3Sq/Qkxxy07kmTOSiAVg+02fLsX9LMPd0nUm2l6tMYjjQ6qlmFWqIDqC/mFy58AoRDdtrmNEVIWp1Grhu9gkMjr/hzqtFxaJxUHJDPj8QlJLB2o+7IKnc8lQaUnwXibDx9lRqHixj8F9z0GJhQCW5zwB9ALv5m/V4JAqET7V5H3dU0XurnesjrFw4iMILC3HnsrMzupXJ56+4hKlZlMZ40K8JxmR8JYFe0s3RR1NU+XBp52zdIeCKqcA2WoL41v6R1cJjZBU4zBEZ5J/61a4fsO9KuSslQAV2vLhlwCNal6XNP7zRzz8mZ/M3YwT4/EEKM1euB66GvG33O4mAXmfXork1ZCitrWr/895gZZzc/LFjmfCcIw0K4Zi6SgHY/Y03gQDJrVw4QZkwhmxKRvuW1nUu6cMcGVX8Nu2DXYZl8UcxLEnJgNajQVy0Xx1bu6ddy3E2RWtjlJtrwIVPA2dMhxiQK52ILFXNKcPz2cY4o2/ArasX8XJOXlWFUqTVaABMF9yysR+MqmVmLtHslKztVu7EHT37jG946vweKR1p58PG6cWfp060Tg9T+FYJyDdUECFO/5vWTAMoy+92IY=

