environment:
  PYTHON: "C:\\Python37-x64"

install:
  - set PATH="%PYTHON%\\Scripts";%PATH%
  - "%PYTHON%\\python.exe -m pip install --upgrade pip setuptools wheel"
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"
  - "%PYTHON%\\python.exe -m pip install certifi https://github.com/pyinstaller/pyinstaller/archive/develop.zip"

build_script:
    - "pyinstaller --additional-hooks-dir=Hooks/ -y -F -i CurseBreaker.ico -n CurseBreaker -c --noupx CurseBreaker.py"

artifacts:
  - path: dist\CurseBreaker.exe
